

name: Az-Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_SSDDG54AB_UCVS }}

      - name: Checkout TF Code
        uses: azure/checkout@v2

      - name: Deploy Terraform Configuration File
        uses: 



